"""empty message

Revision ID: 62032fd3e3e2
Revises: b1a41e75b58b
Create Date: 2021-07-02 23:16:47.275207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62032fd3e3e2'
down_revision = 'b1a41e75b58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_delete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    # ### end Alembic commands ###
